### ISSUE TITLE
How to configure Certificate options?

### ISSUE THREAD

**Issue by tacerus** [93million/certcache#18]
Hello!

I read the documentation provided in the docs/ directory, however could not figure this one out - sorry if I missed something!

I want to specify global certificate options, i.e. to have the server request and deploy ECDSA instead of RSA certificates.
How would I go about configuring that? Do I need to use a config.json? The documentation about the config.json seems to support variables for custom Certbot options, however they seem to be oriented to configuring a CertCache client, whereas I'd like to have the Certbot configuration streamlined from the CertCache server.

Would appreciate any input! Thanks a lot!

**Comment by 93million** [comment]
Hi there @tacerus 

I need to update to a more recent version of Certbot to support ECDSA. I will push an update in the next few days to support this which includes documentation describing how to generate ECDSA certs.

Will update you when it's released :)

**Comment by tacerus** [comment]
Awesome - Thanks a lot!

**Comment by 93million** [comment]
Hey @tacerus sorry for slow response.

I was planning to just give access to the certbot global config file but this would have potentially caused stale caches and would have been awkward and confusing to maintain.

So instead I added support for generating and caching ECDSA certs in [version `0.6.0`](https://github.com/93million/certcache/releases/tag/0.6.0)

Documentation is present at [docs/ECDSA%20Certificates.md](https://github.com/93million/certcache/blob/master/docs/ECDSA%20Certificates.md)

Hope it's useful :)

**Comment by 93million** [comment]
@tacerus ps. if you have time please lemme know if it works for you an i'll close the issue

**Comment by tacerus** [comment]
Big apologies for my slow response as well. I did not realize my responses sent via email did not get through. I have only now gotten to finally try it out and will report back ASAP.

**Comment by tacerus** [comment]
@93million This is amazing! It works great! Thank you so much for the quick implementation and the nice program. Wish I could have gotten back to you sooner. Keep it up!

**Comment by 93million** [comment]
Awesome - great to hear! And please feel free to promote this project if you ever find yourself in such a position :)

**Comment by tacerus** [comment]
Absolutely - currently deploying it for our small NGO - nothing big, but the word is getting out ;-)

**Comment by 93million** [comment]
This makes me happy. Great to hear who's using it and how!
